# Generated by Django 4.2.4 on 2025-05-26 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traductor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TraduccionPalabra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('palabra_original_mexico', models.CharField(max_length=100, unique=True)),
                ('traduccion_argentina', models.CharField(max_length=100)),
                ('traduccion_colombia', models.CharField(max_length=100)),
                ('traduccion_venezuela', models.CharField(max_length=100)),
                ('traduccion_chile', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Traducción de Palabra',
                'verbose_name_plural': 'Traducciones de Palabras',
            },
        ),
    ]
