# Generated by Django 4.2.4 on 2025-05-26 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traductor', '0002_traduccionpalabra'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='traduccionpalabra',
            name='traduccion_argentina',
        ),
        migrations.RemoveField(
            model_name='traduccionpalabra',
            name='traduccion_chile',
        ),
        migrations.RemoveField(
            model_name='traduccionpalabra',
            name='traduccion_colombia',
        ),
        migrations.RemoveField(
            model_name='traduccionpalabra',
            name='traduccion_venezuela',
        ),
        migrations.AddField(
            model_name='traduccionpalabra',
            name='traduccion_ar',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Traducción Argentina'),
        ),
        migrations.AddField(
            model_name='traduccionpalabra',
            name='traduccion_ca',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Traducción Colombia'),
        ),
        migrations.AddField(
            model_name='traduccionpalabra',
            name='traduccion_cl',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Traducción Chile'),
        ),
        migrations.AddField(
            model_name='traduccionpalabra',
            name='traduccion_vz',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Traducción Venezuela'),
        ),
        migrations.AlterModelTable(
            name='traduccionpalabra',
            table='tbl_traducciones',
        ),
    ]
